services:
  # Combined Frontend + Backend Service
  - type: web
    name: emotion-detective-app
    env: node
    buildCommand: |
      cd frontend && npm install && npm run build
      cd ../backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: VITE_API_URL
        value: https://emotion-detective-app.onrender.com
    healthCheckPath: /health
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: emotion-detective-api
          envVarKey: RENDER_EXTERNAL_URL
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
